# -*- mode: python ; coding: utf-8 -*-
# BackFlip.spec
#
# Estrategia: scipy y skimage se incluyen completos (tienen dependencias internas
# en cadena que no se pueden excluir de forma segura). Se excluyen solo paquetes
# completamente ajenos al proyecto.

block_cipher = None

a = Analysis(
    ['BackFlip_GUI.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('luts', 'luts'),
    ],
    hiddenimports=[
        'pylibCZIrw',
        'pylibCZIrw.czi',
        'xmltodict',
        'tifffile',
        'imageio',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # ---- PySide6: excluir modulos Qt no usados ----
        'PySide6.QtNetwork',
        'PySide6.QtSql',
        'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets',
        'PySide6.QtBluetooth',
        'PySide6.QtLocation',
        'PySide6.QtNfc',
        'PySide6.QtPositioning',
        'PySide6.QtPrintSupport',
        'PySide6.QtQml',
        'PySide6.QtQuick',
        'PySide6.QtQuickControls2',
        'PySide6.QtQuickWidgets',
        'PySide6.QtRemoteObjects',
        'PySide6.QtSensors',
        'PySide6.QtSerialBus',
        'PySide6.QtSerialPort',
        'PySide6.QtTest',
        'PySide6.QtWebChannel',
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineQuick',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebSockets',
        'PySide6.QtXml',
        'PySide6.Qt3DAnimation',
        'PySide6.Qt3DCore',
        'PySide6.Qt3DExtras',
        'PySide6.Qt3DInput',
        'PySide6.Qt3DLogic',
        'PySide6.Qt3DRender',
        'PySide6.QtCharts',
        'PySide6.QtDataVisualization',
        'PySide6.QtStateMachine',
        'PySide6.QtConcurrent',
        'PySide6.QtOpenGL',
        'PySide6.QtOpenGLWidgets',

        # ---- Paquetes completamente ajenos al proyecto ----
        'matplotlib',
        'IPython',
        'jupyter',
        'tkinter',
        'PyQt5',
        'PyQt6',
        'wx',
        'pandas',
        'sklearn',
        'sympy',
        'numba',
        'torch',
        'tensorflow',
        'keras',
        'docutils',
        'sphinx',
        'pytest',
        'setuptools',
        'distutils',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BackFlip',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/logo.ico',
)
